/**
 * Thin wrapper around @capawesome-team/capacitor-android-foreground-service.
 *
 * Starts a persistent notification when autovote toggles on so the
 * Android OS keeps the WebView process alive while the phone is
 * locked / app backgrounded. The notification is the only UX
 * difference between "autovote running" on Android vs Electron.
 *
 * No-op on Electron, CLI, and non-Capacitor builds. The plugin is
 * lazy-required so non-Capacitor bundles never resolve it.
 *
 * Scope: this controls ONLY the persistent notification. Since M3 the actual
 * background voting cycle runs natively in AutoVoteService's headless WebView,
 * driven by AlarmManager — not a JS setInterval (which dies with the WebView).
 * Doze-exact 1-min precision is handled there via setExactAndAllowWhileIdle();
 * see AutoVoteService.kt and NativeAutovoteBridge.ts.
 *
 * Limitations (documented for the next person who looks at this):
 *  - Vendor battery killers (Samsung / Xiaomi / OnePlus) may still kill the
 *    service. First-run onboarding should prompt the user to exclude the app
 *    from battery optimization per-vendor.
 */

import * as runtime from '../runtime';
import * as logger from '../logger';

import type { ForegroundServicePlugin } from '@capawesome-team/capacitor-android-foreground-service';

let plugin: ForegroundServicePlugin | null = null;
const NOTIFICATION_ID = 27782; // arbitrary stable id
const APP_NAME = 'GuruShots Auto Vote';

const getPlugin = () => {
    if (!runtime.isCapacitor()) return null;
    if (plugin) return plugin;
    try {
        plugin = (
            require('@capawesome-team/capacitor-android-foreground-service') as typeof import('@capawesome-team/capacitor-android-foreground-service')
        ).ForegroundService;
        return plugin;
    } catch (err) {
        logger.withCategory('voting').warning('ForegroundService plugin unavailable', (err as Error).message);
        return null;
    }
};

const requestPermissions = async () => {
    const fs = getPlugin();
    if (!fs) return { display: 'granted' };
    try {
        const status = await fs.checkPermissions();
        if (status?.display === 'granted') return status;
        return await fs.requestPermissions();
    } catch (err) {
        logger.withCategory('voting').warning('ForegroundService permission check failed', (err as Error).message);
        return { display: 'denied' };
    }
};

/**
 * Start the foreground service with a "running" notification.
 * Safe to call multiple times — the plugin updates if already running.
 */
const start = async ({ title = APP_NAME, body = 'Auto-vote running' }: { title?: string; body?: string } = {}) => {
    const fs = getPlugin();
    if (!fs) return false;
    try {
        await requestPermissions();
        await fs.startForegroundService({
            id: NOTIFICATION_ID,
            title,
            body,
            // smallIcon must be a drawable name in android/app/src/main/res/drawable*/.
            // ic_launcher_foreground is generated by Capacitor and present in the project.
            smallIcon: 'ic_launcher_foreground',
        });
        return true;
    } catch (err) {
        logger.withCategory('voting').error('startForegroundService failed', (err as Error).message);
        return false;
    }
};

/**
 * Update the notification text (e.g. last cycle time, next cycle ETA).
 * Cheap on Android — no permission re-prompt.
 */
const update = async ({ title = APP_NAME, body }: { title?: string; body?: string }) => {
    const fs = getPlugin();
    if (!fs || !body) return;
    try {
        await fs.updateForegroundService({
            id: NOTIFICATION_ID,
            title,
            body,
            smallIcon: 'ic_launcher_foreground',
        });
    } catch (err) {
        // updateForegroundService throws if the service isn't running yet — ignore.
        logger.withCategory('voting').debug('updateForegroundService skipped', (err as Error).message);
    }
};

/**
 * Stop the foreground service. Safe to call when not running.
 */
const stop = async () => {
    const fs = getPlugin();
    if (!fs) return;
    try {
        await fs.stopForegroundService();
    } catch (err) {
        logger.withCategory('voting').error('stopForegroundService failed', (err as Error).message);
    }
};

export { start, update, stop, requestPermissions };
