/**
 * Thin wrapper around @capawesome-team/capacitor-android-foreground-service.
 *
 * Starts a persistent notification when autovote toggles on so the
 * Android OS keeps the WebView process alive while the phone is
 * locked / app backgrounded. The notification is the only UX
 * difference between "autovote running" on Android vs Electron.
 *
 * No-op on Electron, CLI, and non-Capacitor builds. The plugin is
 * lazy-required so non-Capacitor bundles never resolve it.
 *
 * Limitations (documented for the next person who looks at this):
 *  - The plugin keeps the process alive but does not run JS in the
 *    background by itself. The cycle loop continues to live in the
 *    React tree's setInterval; Doze / battery-saver can still pause
 *    timers when the phone is in deep sleep. For 1-min last-minute
 *    precision we'd need AlarmManager.setExactAndAllowWhileIdle()
 *    via a custom plugin or Capacitor 8's BackgroundRunner.
 *  - Vendor battery killers (Samsung / Xiaomi / OnePlus) may still
 *    kill the service. First-launch onboarding should prompt the
 *    user to whitelist the app per-vendor.
 */

const runtime = require('../runtime');
const logger = require('../logger');

let plugin = null;
const NOTIFICATION_ID = 27782; // arbitrary stable id
const APP_NAME = 'GuruShots Auto Vote';

const getPlugin = () => {
    if (!runtime.isCapacitor()) return null;
    if (plugin) return plugin;
    try {
        plugin = require('@capawesome-team/capacitor-android-foreground-service').ForegroundService;
        return plugin;
    } catch (err) {
        logger.withCategory('voting').warning('ForegroundService plugin unavailable', err.message);
        return null;
    }
};

const requestPermissions = async () => {
    const fs = getPlugin();
    if (!fs) return { display: 'granted' };
    try {
        const status = await fs.checkPermissions();
        if (status?.display === 'granted') return status;
        return await fs.requestPermissions();
    } catch (err) {
        logger.withCategory('voting').warning('ForegroundService permission check failed', err.message);
        return { display: 'denied' };
    }
};

/**
 * Start the foreground service with a "running" notification.
 * Safe to call multiple times — the plugin updates if already running.
 */
const start = async ({ title = APP_NAME, body = 'Auto-vote running' } = {}) => {
    const fs = getPlugin();
    if (!fs) return false;
    try {
        await requestPermissions();
        await fs.startForegroundService({
            id: NOTIFICATION_ID,
            title,
            body,
            // smallIcon must be a drawable name in android/app/src/main/res/drawable*/.
            // ic_launcher_foreground is generated by Capacitor and present in the project.
            smallIcon: 'ic_launcher_foreground',
        });
        return true;
    } catch (err) {
        logger.withCategory('voting').error('startForegroundService failed', err.message);
        return false;
    }
};

/**
 * Update the notification text (e.g. last cycle time, next cycle ETA).
 * Cheap on Android — no permission re-prompt.
 */
const update = async ({ title = APP_NAME, body }) => {
    const fs = getPlugin();
    if (!fs || !body) return;
    try {
        await fs.updateForegroundService({
            id: NOTIFICATION_ID,
            title,
            body,
            smallIcon: 'ic_launcher_foreground',
        });
    } catch (err) {
        // updateForegroundService throws if the service isn't running yet — ignore.
        logger.withCategory('voting').debug('updateForegroundService skipped', err.message);
    }
};

/**
 * Stop the foreground service. Safe to call when not running.
 */
const stop = async () => {
    const fs = getPlugin();
    if (!fs) return;
    try {
        await fs.stopForegroundService();
    } catch (err) {
        logger.withCategory('voting').error('stopForegroundService failed', err.message);
    }
};

module.exports = {
    start,
    update,
    stop,
    requestPermissions,
};
