/**
 * Cross-platform loader for the static word-vector lexicon
 * (src/assets/semantic-vectors.json, generated by scripts/build-lexicon.ts).
 *
 * The file is loaded as a RUNTIME ASSET on every platform — it is never
 * imported into a JS bundle, so the renderer / headless / capacitor
 * size-limit budgets are untouched. Resolution per platform:
 *   - Android WebView (Capacitor page + headless background service): fetch()
 *     from the webDir (dist/), where build:prep copies the file.
 *   - CLI single binary (Node SEA): node:sea.getAsset().
 *   - CLI from source + Electron (dev and packaged .asar): fs read of the
 *     committed src/assets copy.
 *
 * Any failure resolves to null (cached), so the caller falls back to
 * lexical-only matching — a missing or unreadable asset is a no-op, never a
 * crash. Mirrors the node:sea detection guard already used in logger.ts.
 */

import * as runtime from '../../runtime';
import { appPath } from '../../appPaths';

import type { RawLexicon } from '../../types/semantic';

const ASSET_NAME = 'semantic-vectors.json';

// undefined = not attempted yet, null = attempted and unavailable, object = loaded
let cached: RawLexicon | null | undefined;
let inflight: Promise<RawLexicon | null> | null = null;

const loadViaFetch = async (): Promise<RawLexicon | null> => {
    // Relative URL resolves against the WebView document served from the webDir.
    const res = await fetch(ASSET_NAME);
    if (!res || !res.ok) throw new Error(`fetch ${ASSET_NAME}: HTTP ${res && res.status}`);
    return res.json() as Promise<RawLexicon>;
};

const loadViaNode = (): RawLexicon | null => {
    // CLI single binary embeds the lexicon in the SEA blob.
    try {
        const sea = require('node:sea') as typeof import('node:sea');
        if (sea.isSea()) return JSON.parse(sea.getAsset(ASSET_NAME, 'utf8')) as RawLexicon;
    } catch {
        // node:sea unavailable or not a SEA build — fall through to the fs read.
    }
    const fs = require('node:fs') as typeof import('node:fs');
    return JSON.parse(fs.readFileSync(appPath('src', 'assets', ASSET_NAME), 'utf8')) as RawLexicon;
};

/**
 * Load and cache the parsed lexicon asset. Concurrent callers share one
 * in-flight load. Returns the parsed object, or null when unavailable.
 *
 * @returns the parsed JSON, unchecked (buildTable validates it)
 */
const loadLexiconAsset = async (): Promise<RawLexicon | null> => {
    if (cached !== undefined) return cached;
    if (!inflight) {
        inflight = (async () => {
            try {
                const useFetch = runtime.isCapacitor() || runtime.isHeadlessService();
                cached = useFetch ? await loadViaFetch() : loadViaNode();
            } catch {
                cached = null;
            }
            return cached;
        })();
    }
    return inflight;
};

// Test-only: clear the memoized asset so a test can swap the underlying source.
const __resetForTests = () => {
    cached = undefined;
    inflight = null;
};

export { loadLexiconAsset, ASSET_NAME, __resetForTests };
